apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: aws-spring-container
          image: aravind777/aws-spring
          ports:
            - containerPort: 5000

